swagger: "2.0"
info:
  version: "0.0.1"
  title: Node Render
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /render:
    # binds a127 app logic to a route
    x-swagger-router-controller: render


    post:
      description: Возвращает HTML страницу после предобработки Javascript
      # used as the method name of the controller
      operationId: renderHTML
      parameters:
        - name: url
          in: body
          description:  URL страницы
          required: true
          schema:
            $ref: "#/definitions/Render"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RenderResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  Render:
    required:
      - url
    properties:
      url:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  RenderResponse:
    properties:
      message:
        type: string
    required:
      - message
